version: '3'
services:
  web:
    image: wordpress:4.8.1
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_PASSWORD=some_password
      - WORDPRESS_DB_HOST=db:3306
  db:
    image: mysql:5.7.19
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
